version: '3.7'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./database 
      dockerfile: dockerfile
    command: npm start    
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./centromedico
      dockerfile: dockerfile
    command: npm run dev
    depends_on:
      - backend
    ports:
      - "2000:2000"